Repository jualat/CleanRLHF, pull requests merged in 2024-12, with the labels that each got.

#15 14-implement-the-bpref-teacher
  framework/reward_net.py
  framework/sac_rlhf.py
  framework/teacher.py
Labels: research

#26 Skip already existing videos
  framework/video_recorder.py
Labels: enhancement

#27 19-implement-unsupervised-exploration
  framework/reward_net.py
  framework/sac_rlhf.py
  framework/unsupervised_exploration.py
  framework/video_recorder.py
  pyproject.toml
Labels: enhancement, research

#33 18: Fix
  framework/sac_rlhf.py
Labels: bug

#12 1: add pre-commit with default black config
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  framework/reward_net.py
  poetry.lock
  pyproject.toml
Labels: tooling

#44 43-Swimmer-v4-error-fix
  framework/replay_buffer.py
  framework/sac_rlhf.py
Labels: bug

#45 42-set-up-weights-and-biases
  framework/.gitignore
  framework/README.md
  framework/reward_net.py
  framework/sac_rlhf.py
Labels: documentation

#59 58-fix-video-recorder
  framework/replay_buffer.py
  framework/reward_net.py
  framework/sac_rlhf.py
  framework/sampling.py
  framework/video_recorder.py
Labels: bug

#60 46 evaluation for policy
  framework/evaluation.py
  framework/sac_rlhf.py
  pyproject.toml
Labels: enhancement
