Repository jualat/CleanRLHF, pull requests merged in 2025-01, with the labels that each got.

#61 22-split-up-the-main-file
  framework/actor.py
  framework/critic.py
  framework/env.py
  framework/evaluation.py
  framework/replay_buffer.py
  framework/sac_rlhf.py
  framework/video_recorder.py
  poetry.lock
  pyproject.toml
Labels: maintenance

#66 64-add-sweep
  framework/README.md
  framework/replay_buffer.py
  framework/sac_rlhf.py
  framework/sweep.py
  framework/sweep_config/hopper_sweep.yaml
  poetry.lock
  pyproject.toml
Labels: enhancement

#74 68: update dependencies
  framework/reward_net.py
  framework/sac_rlhf.py
  framework/video_recorder.py
  poetry.lock
  pyproject.toml
Labels: maintenance

#77 67: Add documentation to methods
  framework/actor.py
  framework/critic.py
  framework/env.py
  framework/evaluation.py
  framework/replay_buffer.py
  framework/reward_net.py
  framework/sac_rlhf.py
  framework/sampling.py
  framework/sweep_config/ant_sweep.yaml
  framework/sweep_config/half_cheetah_sweep.yaml
  framework/sweep_config/hopper_sweep.yaml
  framework/sweep_config/humanoid_standup_sweep.yaml
  framework/sweep_config/humanoid_sweep.yaml
  framework/sweep_config/inverted_double_pendulum_sweep.yaml
  framework/sweep_config/inverted_pendulum_sweep.yaml
  framework/sweep_config/pusher_sweep.yaml
  framework/sweep_config/reacher_sweep.yaml
  framework/sweep_config/swimmer_sweep.yaml
  framework/sweep_config/walker_2d_sweep.yaml
Labels: documentation

#75 69-implement-SURF
  framework/preference_buffer.py
  framework/replay_buffer.py
  framework/reward_net.py
  framework/sac_rlhf.py
  framework/sampling.py
  framework/teacher.py
  framework/video_recorder.py
  script.sh
Labels: enhancement

#96 94-add-minibatch-option
  framework/preference_buffer.py
  framework/reward_net.py
  framework/sac_rlhf.py
  framework/sampling.py
  framework/teacher.py
Labels: enhancement

#119 Fix handling of Neither in human feedback
  framework/feedback.py
Labels: bug
